#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "\n## Fetching main branch...\n"
git pull origin main
git pull origin dev
echo -e  "\n## Main branch fetched ...\n"

# echo -e "\n## Building Project...\n"
# npm run build
# echo -e  "\n## Project built ...\n"
